<a href="https://colab.research.google.com/github/gungungoyal314/PythonLearn/blob/main/pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
data = {

        'experience':[1,2,3,4,5,6,7,8,9,10],
        'salary':[100,200,300,400,500,600,700,800,900,1000]
}

df = pd.DataFrame(data)
print(df)



print(df.head())  # starting 5 rows

print(df.tail())  # last 5 rows

   experience  salary
0           1     100
1           2     200
2           3     300
3           4     400
4           5     500
5           6     600
6           7     700
7           8     800
8           9     900
9          10    1000
   experience  salary
0           1     100
1           2     200
2           3     300
3           4     400
4           5     500
   experience  salary
5           6     600
6           7     700
7           8     800
8           9     900
9          10    1000

In [7]:
print(df.head(-6))

   experience  salary
0           1     100
1           2     200
2           3     300
3           4     400

In [10]:
df.tail(3)

   experience  salary
3           4     400
4           5     500
5           6     600
6           7     700
7           8     800
8           9     900
9          10    1000

In [11]:
print(df.shape)

(10, 2)

In [12]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   experience  10 non-null     int64
 1   salary      10 non-null     int64
dtypes: int64(2)
memory usage: 292.0 bytes
None

In [17]:
# rename
df.rename(columns={"experience": "hands_on_experience","salary":"amount"}, inplace=True)
print(df)

   hands_on_experience  amount
0                    1     100
1                    2     200
2                    3     300
3                    4     400
4                    5     500
5                    6     600
6                    7     700
7                    8     800
8                    9     900
9                   10    1000

In [18]:

# describe in pandas
df.describe()

       hands_on_experience       amount
count             10.00000    10.000000
mean               5.50000   550.000000
std                3.02765   302.765035
min                1.00000   100.000000
25%                3.25000   325.000000
50%                5.50000   550.000000
75%                7.75000   775.000000
max               10.00000  1000.000000

In [26]:
!pip install pandas
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

df = pd.DataFrame(data)

print(df)

df.head()
df.tail()
df.shape
df.info()
df.describe()
df.rename(columns={"Emp_ID": "Employee_ID"}, inplace=True)
print(df)

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      6 non-null      int64
 1   Name        6 non-null      object
 2   Department  6 non-null      object
 3   Salary      6 non-null      int64
 4   Experience  6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes
   Employee_ID  Name Department  Salary  Experience
0          101  Amit         IT   50000           2
1          102  Riya         HR   45000           3
2          103   Raj    Finance   60000           5
3          104  Sara         IT   55000           4
4          105  John      Sales   48000           1
5          106  Neha         HR   52000           3

In [33]:
# operations on columns
# select columnns
print(df["Employee_ID"])

# select col store in variable
abc = df["Employee_ID"]
print(abc)

# cols value change
df["Employee_ID"] = [11, 12, 13, 14, 15, 16]
print(df)


df["Employee_ID"] = df["Employee_ID"] - 100
print(df)


# add new col
df['Amount'] = df['Salary'] * 1000
print(df)

0   -89
1   -88
2   -87
3   -86
4   -85
5   -84
Name: Employee_ID, dtype: int64
0   -89
1   -88
2   -87
3   -86
4   -85
5   -84
Name: Employee_ID, dtype: int64
   Employee_ID  Name Department  Salary  Experience  Amount
0           11  Amit         IT   50000           2   50000
1           12  Riya         HR   45000           3   45000
2           13   Raj    Finance   60000           5   60000
3           14  Sara         IT   55000           4   55000
4           15  John      Sales   48000           1   48000
5           16  Neha         HR   52000           3   52000
   Employee_ID  Name Department  Salary  Experience  Amount
0          -89  Amit         IT   50000           2   50000
1          -88  Riya         HR   45000           3   45000
2          -87   Raj    Finance   60000           5   60000
3          -86  Sara         IT   55000           4   55000
4          -85  John      Sales   48000           1   48000
5          -84  Neha         HR   52000           3   52000
   Employee_ID  Name Department  Salary  Experience    Amount
0          -89  Amit         IT   50000           2  50000000
1          -88  Riya         HR   45000           3  45000000
2          -87   Raj    Finance   60000           5  60000000
3          -86  Sara         IT   55000           4  55000000
4          -85  John      Sales   48000           1  48000000
5          -84  Neha         HR   52000           3  52000000

In [44]:
# drop column
df.drop(columns=["Amount"], inplace=True, errors='ignore')
print(df)

   Employee_ID  Salary  Experience
0          -89   50000           2
1          -88   45000           3
2          -87   60000           5
3          -86   55000           4
4          -85   48000           1
5          -84   52000           3

In [42]:


# drop multi cols
df.drop(["Name","Department"],axis=1,inplace=True, errors='ignore')
print(df)

   Employee_ID  Salary  Experience
0          -89   50000           2
1          -88   45000           3
2          -87   60000           5
3          -86   55000           4
4          -85   48000           1
5          -84   52000           3

In [52]:
# operations on rows
# loc  ---> label wise

import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

df = pd.DataFrame(data)
print(df)

print(df.loc[3,"Name"])


# iloc
print(df.iloc[3,1])

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
Sara
Sara

In [59]:
# multiple rows
print(df.iloc[0:2])

# get rows
print(df.loc[[0,1,2]])

# get rows using iloc
print(df.iloc[[1,2,3]])

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
   Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4

In [62]:
# multi rows and cols
print(df.iloc[[0,1],[0,1]])

   Emp_ID  Name
0     101  Amit
1     102  Riya

In [70]:
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

df = pd.DataFrame(data)

print(df)


# how to use filter

print(df[df["Emp_ID"] > 104])
print(df[df["Emp_ID"] == 106])
# 30000 to 50000
# print(df[(condition one) & (condition 2)])
print(df[(df['Salary']> 30000) & (df['Salary'] < 50000)])

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   45000           3
4     105  John      Sales   48000           1

In [78]:
# sorting ascending
print(df.sort_values('Salary',ascending = False))

# two cols
print(df.sort_values(["Salary","Experience"]))

   Emp_ID  Name Department  Salary  Experience
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
5     106  Neha         HR   52000           3
0     101  Amit         IT   50000           2
4     105  John      Sales   48000           1
1     102  Riya         HR   45000           3
   Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   45000           3
4     105  John      Sales   48000           1
0     101  Amit         IT   50000           2
5     106  Neha         HR   52000           3
3     104  Sara         IT   55000           4
2     103   Raj    Finance   60000           5